# Generated by Django 5.0.3 on 2024-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='sign_PhoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
