# Generated by Django 5.0.3 on 2024-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Hotels', models.CharField(max_length=100)),
                ('UserRating', models.CharField(max_length=100)),
                ('PropertyType', models.CharField(max_length=100)),
                ('Chains', models.CharField(max_length=100)),
                ('Amenities', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'custom_table',
            },
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pid', models.IntegerField(max_length=10, unique=True)),
                ('price', models.IntegerField(max_length=100)),
                ('imgurl', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'destination_table',
            },
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pid', models.IntegerField(max_length=10, unique=True)),
                ('price', models.IntegerField(max_length=100)),
                ('imgurl', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'packages_table',
            },
        ),
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_FullName', models.CharField(max_length=100)),
                ('sign_Username', models.CharField(max_length=100)),
                ('sign_Email', models.EmailField(max_length=100, unique=True)),
                ('sign_PhoneNumber', models.BigIntegerField(max_length=100)),
                ('sign_password', models.CharField(max_length=100)),
                ('sign_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
    ]
